version: apps/v1
kind: Deployment 
metadata:
  name: hello-world-deployment
spec:
  replicas: 3
  selector: 
    matchLabels:  
      app: express-hello-world
  template: 
    metadata: 
      name: hello-world-pod
      labels: 
        app: express-hello-world 
    spec: 
      containers: 
      - name: hello-world
        image: akarshhosmane/hellonode-app:latest
        ports:
        - containerPort: 8080