apiVersion: v1
kind: Pod
metadata:
  name: hello-world
  labels:
    app: express-hello-world
spec:
  containers:
  - name: hello-world
    image: akarshhosmane/hellonode-app:latest
    ports:
    - containerPort: 8080
    