apiVersion: v1
kind: ReplicationSet
metadata:
  name: hello-world-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: express-hello-world
  template:
    metadata:
      labels:
        app: express-hello-world
    spec:
      containers:
      - name: hello-world
        image: akarshhosmane/hellonode-app:latest
        ports:
        - containerPort: 8080